// ABChapterize - mark chapter starts in audiobooks using Whisper speech recognition
// Copyright (c) 2026 Jan O. Gretza. Written with Claude (Anthropic).
// MIT license - see the LICENSE file in the repository root.

using System.Security.Cryptography;
using System.Text;
using Xunit;

namespace ABChapterize.Tests;

/// <summary>
/// Keeps the HTML documentation under <c>doc/html</c> in step with the Markdown it was generated
/// from, on the machine that generates it.
/// </summary>
/// <remarks>
/// <para>
/// <b><c>doc/html</c> is no longer committed</b> (2026-08-28, the user's call): the pages are
/// published at <c>abchapterize.anetos.de</c>, which makes a second copy in the repository
/// redundant, and the Impressum among them carries a private postal address that has no business
/// being in a public history. So these tests now run against whatever the local clone happens to
/// have generated, and <b>do nothing at all where nothing has been generated</b> - which is the
/// normal state of a fresh clone, not a failure. The check that actually gates publishing moved
/// to <c>tools\publish-docs.ps1</c>, which re-reads the same stamp and refuses to upload stale
/// pages.
/// </para>
/// <para>
/// The pages are generated by a tool that lives outside this repository (<c>tools\docgen</c>,
/// which is gitignored here), so nothing in a clone can regenerate them by itself and nothing
/// in a build would notice them going stale. What a clone can do is compare: the generator
/// leaves a <c>sources.sha256</c> naming every Markdown file it read and what it hashed to, and
/// these tests re-hash those files.
/// </para>
/// <para>
/// A failure here does not mean the HTML is wrong. It means <c>doc\manual.md</c> (or one of its
/// companions) has moved on since the pages were last made, and the fix is to run the generator
/// again before publishing. <c>ConstantsDocTests</c> is the same idea applied to
/// <c>doc\constants.md</c>, which is still committed.
/// </para>
/// </remarks>
public sealed class HtmlDocsTests
{
    /// <summary>The generator's record of what it read, relative to the repository root.</summary>
    private const string StampPath = "doc/html/sources.sha256";

    private static string RepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "ABChapterize.csproj")))
            dir = dir.Parent;
        Assert.NotNull(dir);
        return dir!.FullName;
    }

    private static string Resolve(string repoRelative) =>
        Path.Combine(RepoRoot(), repoRelative.Replace('/', Path.DirectorySeparatorChar));

    /// <summary>
    /// Whether this clone has generated the set at all. Absent is the ordinary state now that the
    /// pages are not committed, so every test below returns rather than failing - the alternative
    /// would be a suite that cannot pass in a fresh clone, which teaches people to ignore it.
    /// </summary>
    private static bool NotGeneratedHere => !File.Exists(Resolve(StampPath));

    /// <summary>The stamp as "repo-relative path" -&gt; "the hash recorded for it".</summary>
    private static Dictionary<string, string> Stamp()
    {
        var stamp = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var line in File.ReadAllLines(Resolve(StampPath)))
        {
            var separator = line.IndexOf("  ", StringComparison.Ordinal);
            if (separator > 0) stamp[line[(separator + 2)..].Trim()] = line[..separator];
        }
        return stamp;
    }

    /// <summary>
    /// The same hash the generator computes: over the text with line endings normalized, never
    /// over the bytes. The repository is checked out with <c>core.autocrlf=true</c>, so the same
    /// commit is CRLF on Windows and LF under WSL, and a byte hash would fail on whichever
    /// machine did not generate the pages.
    /// </summary>
    private static string Hash(string path)
    {
        var text = File.ReadAllText(path).ReplaceLineEndings("\n");
        return Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(text)));
    }

    [Fact]
    public void TheGeneratedPages_AreUpToDateWithTheirSources()
    {
        if (NotGeneratedHere) return;

        var stale = Stamp()
            .Where(entry => Hash(Resolve(entry.Key)) != entry.Value)
            .Select(entry => entry.Key)
            .ToList();

        Assert.True(stale.Count == 0,
                    $"doc/html is out of date with {string.Join(", ", stale)}. " +
                    "Regenerate it with \"dotnet run --project tools\\docgen\".");
    }

    [Fact]
    public void EveryMarkdownFileUnderDoc_IsPartOfTheGeneratedSet()
    {
        if (NotGeneratedHere) return;

        // A new document nobody told the generator about would render nowhere and be linked
        // from nothing, which is the one kind of staleness a hash cannot see.
        var stamped = Stamp().Keys.ToHashSet(StringComparer.OrdinalIgnoreCase);
        var missing = Directory.EnumerateFiles(Path.Combine(RepoRoot(), "doc"), "*.md")
                               .Select(path => "doc/" + Path.GetFileName(path))
                               .Where(path => !stamped.Contains(path))
                               .ToList();

        Assert.True(missing.Count == 0,
                    $"{string.Join(", ", missing)} has no HTML rendering. Add it to the Sources " +
                    "list in tools\\docgen and regenerate doc/html.");
    }

    [Fact]
    public void EveryStampedSource_StillExists()
    {
        if (NotGeneratedHere) return;

        var gone = Stamp().Keys.Where(path => !File.Exists(Resolve(path))).ToList();

        Assert.True(gone.Count == 0,
                    $"doc/html was generated from {string.Join(", ", gone)}, which no longer exists.");
    }
}
